version: "3.7"
 
services:
  fluentd:
      container_name: fluentd
      image: ambicaaas/aas_fluentd
      ports:
        - "24224:24224"
        - "24224:24224/udp"
      logging:
        driver: "local"
      restart: always